version: '3'
services:
  postgres:
    image: postgres:12.3
    volumes:
    - ./initial_sql_script.sql:/docker-entrypoint-initdb.d/initial_sql_script.sql
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root